nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        max_age: 3600
        expose_headers: []
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/': ~
